import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('api', {
    registry: {
        get: (hive: string, path: string, name: string) => ipcRenderer.invoke('registry:get', hive, path, name),
        set: (hive: string, path: string, name: string, value: any, type: string) => ipcRenderer.invoke('registry:set', hive, path, name, value, type),
        delete: (hive: string, path: string, name: string) => ipcRenderer.invoke('registry:delete', hive, path, name),
        backup: () => ipcRenderer.invoke('registry:backup'),
        restoreAll: () => ipcRenderer.invoke('registry:restoreAll'),
        restoreLast: () => ipcRenderer.invoke('registry:restoreLast'),
    },
    powerPlan: {
        create: () => ipcRenderer.invoke('powerplan:create'),
        activate: () => ipcRenderer.invoke('powerplan:activate'),
        deactivate: () => ipcRenderer.invoke('powerplan:deactivate'),
        isActive: () => ipcRenderer.invoke('powerplan:isActive'),
        exists: () => ipcRenderer.invoke('powerplan:exists'),
        getActive: () => ipcRenderer.invoke('powerplan:getActive'),
        listAll: () => ipcRenderer.invoke('powerplan:listAll'),
        activatePlanByGuid: (guid: string) => ipcRenderer.invoke('powerplan:activateByGuid', guid),
        setTimerResolution: (ns: number) => ipcRenderer.invoke('powerplan:setTimer', ns),
        getTimerResolution: () => ipcRenderer.invoke('powerplan:getTimer'),
        applyProfile: (p: string) => ipcRenderer.invoke('powerplan:applyProfile', p),
        generateEnergyReport: () => ipcRenderer.invoke('powerplan:energyReport'),
        generateBatteryReport: () => ipcRenderer.invoke('powerplan:batteryReport'),
        generateSleepStudy: () => ipcRenderer.invoke('powerplan:sleepStudy'),
        exportPlan: (path: string) => ipcRenderer.invoke('powerplan:export', path),
        importPlan: (path: string) => ipcRenderer.invoke('powerplan:import', path),
        delete: () => ipcRenderer.invoke('powerplan:delete'),
    },
    system: {
        getCpuUsage: () => ipcRenderer.invoke('system:cpuUsage'),
        getRamUsage: () => ipcRenderer.invoke('system:ramUsage'),
        getDiskIO: () => ipcRenderer.invoke('system:diskIO'),
        getNetworkSpeed: () => ipcRenderer.invoke('system:networkSpeed'),
        getFullInfo: () => ipcRenderer.invoke('system:fullInfo'),
        getProcesses: () => ipcRenderer.invoke('system:processes'),
        killProcess: (pid: number) => ipcRenderer.invoke('system:killProcess', pid),
        setProcessPriority: (pid: number, p: number) => ipcRenderer.invoke('system:setPriority', pid, p),
        openPath: (p: string) => ipcRenderer.invoke('system:openPath', p),
        runTool: (cmd: string) => ipcRenderer.invoke('system:runTool', cmd),
    },
    services: {
        list: () => ipcRenderer.invoke('services:list'),
        setStartup: (name: string, mode: string) => ipcRenderer.invoke('services:setStartup', name, mode),
        start: (name: string) => ipcRenderer.invoke('services:start', name),
        stop: (name: string) => ipcRenderer.invoke('services:stop', name),
        applyRecommended: () => ipcRenderer.invoke('services:applyRecommended'),
    },
    network: {
        getTcpParams: () => ipcRenderer.invoke('network:getTcpParams'),
        setTcpParam: (name: string, val: any) => ipcRenderer.invoke('network:setTcpParam', name, val),
        runNetsh: (args: string) => ipcRenderer.invoke('network:netsh', args),
        flushDns: () => ipcRenderer.invoke('network:flushDns'),
        resetWinsock: () => ipcRenderer.invoke('network:resetWinsock'),
        resetTcpIp: () => ipcRenderer.invoke('network:resetTcpIp'),
        setDns: (adapter: string, p: string, s: string) => ipcRenderer.invoke('network:setDns', adapter, p, s),
        getAdapters: () => ipcRenderer.invoke('network:getAdapters'),
        pingTest: (host: string) => ipcRenderer.invoke('network:ping', host),
        detectMtu: () => ipcRenderer.invoke('network:detectMtu'),
        setMtu: (adapter: string, size: number) => ipcRenderer.invoke('network:setMtu', adapter, size),
        getOpenPorts: () => ipcRenderer.invoke('network:openPorts'),
        tracert: (host: string) => ipcRenderer.invoke('network:tracert', host),
        nslookup: (host: string) => ipcRenderer.invoke('network:nslookup', host),
    },
    cleaner: {
        scan: (categories: string[]) => ipcRenderer.invoke('cleaner:scan', categories),
        clean: (categories: string[]) => ipcRenderer.invoke('cleaner:clean', categories),
        scanBrowsers: () => ipcRenderer.invoke('cleaner:scanBrowsers'),
        cleanBrowsers: (browsers: string[], types: string[]) => ipcRenderer.invoke('cleaner:cleanBrowsers', browsers, types),
        getLargeFiles: (path: string, minSize: number) => ipcRenderer.invoke('cleaner:largeFiles', path, minSize),
        getDiskUsage: (drive: string) => ipcRenderer.invoke('cleaner:diskUsage', drive),
        scanRegistry: () => ipcRenderer.invoke('cleaner:scanRegistry'),
        cleanRegistry: (items: any[]) => ipcRenderer.invoke('cleaner:cleanRegistry', items),
        emptyRecycleBin: () => ipcRenderer.invoke('cleaner:emptyRecycleBin'),
    },
    startup: {
        list: () => ipcRenderer.invoke('startup:list'),
        toggle: (id: string, enabled: boolean) => ipcRenderer.invoke('startup:toggle', id, enabled),
        delete: (id: string) => ipcRenderer.invoke('startup:delete', id),
        add: (name: string, path: string) => ipcRenderer.invoke('startup:add', name, path),
        refresh: () => ipcRenderer.invoke('startup:list'),
    },
    winget: {
        isInstalled: () => ipcRenderer.invoke('winget:isInstalled'),
        listInstalled: () => ipcRenderer.invoke('winget:listInstalled'),
        install: (id: string) => ipcRenderer.invoke('winget:install', id),
        uninstall: (id: string) => ipcRenderer.invoke('winget:uninstall', id),
        upgradeAll: () => ipcRenderer.invoke('winget:upgradeAll'),
        search: (query: string) => ipcRenderer.invoke('winget:search', query),
        checkUpdate: (id: string) => ipcRenderer.invoke('winget:checkUpdate', id),
    },
    repair: {
        runSfc: () => ipcRenderer.invoke('repair:sfc'),
        runDism: (action: string) => ipcRenderer.invoke('repair:dism', action),
        createRestorePoint: (desc: string) => ipcRenderer.invoke('repair:createRestorePoint', desc),
        listRestorePoints: () => ipcRenderer.invoke('repair:listRestorePoints'),
        resetNetwork: () => ipcRenderer.invoke('repair:resetNetwork'),
        resetWindowsUpdate: () => ipcRenderer.invoke('repair:resetWU'),
        wsreset: () => ipcRenderer.invoke('repair:wsreset'),
        reregisterApps: () => ipcRenderer.invoke('repair:reregisterApps'),
        fixHosts: () => ipcRenderer.invoke('repair:fixHosts'),
        rebuildIconCache: () => ipcRenderer.invoke('repair:iconCache'),
        checkDisk: (drive: string) => ipcRenderer.invoke('repair:chkdsk', drive),
        runMemDiag: () => ipcRenderer.invoke('repair:memdiag'),
    },
    advanced: {
        getInstalledApps: () => ipcRenderer.invoke('advanced:getApps'),
        removeApps: (names: string[]) => ipcRenderer.invoke('advanced:removeApps', names),
        getWindowsFeatures: () => ipcRenderer.invoke('advanced:getFeatures'),
        toggleFeature: (name: string, enable: boolean) => ipcRenderer.invoke('advanced:toggleFeature', name, enable),
        runBcdedit: (args: string) => ipcRenderer.invoke('advanced:bcdedit', args),
        enableGodMode: () => ipcRenderer.invoke('advanced:godMode'),
        changeComputerName: (name: string) => ipcRenderer.invoke('advanced:computerName', name),
    },
    benchmark: {
        runCpu: () => ipcRenderer.invoke('benchmark:cpu'),
        runMemory: () => ipcRenderer.invoke('benchmark:memory'),
        runDisk: (drive: string) => ipcRenderer.invoke('benchmark:disk', drive),
    },
    backup: {
        export: (path: string) => ipcRenderer.invoke('backup:export', path),
        import: (path: string) => ipcRenderer.invoke('backup:import', path),
        undoAll: () => ipcRenderer.invoke('backup:undoAll'),
        undoLast: () => ipcRenderer.invoke('backup:undoLast'),
    },
    admin: {
        isAdmin: () => ipcRenderer.invoke('admin:isAdmin'),
        relaunchAsAdmin: () => ipcRenderer.send('admin:relaunch'),
    },
    window: {
        minimize: () => ipcRenderer.send('window:minimize'),
        maximize: () => ipcRenderer.send('window:maximize'),
        close: () => ipcRenderer.send('window:close'),
        isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
    },
    updates: {
        checkForUpdates: () => ipcRenderer.invoke('updates:check'),
        downloadUpdate: () => ipcRenderer.send('updates:download'),
        installUpdate: () => ipcRenderer.send('updates:install'),
    },
    onLogLine: (cb: (line: string) => void) => ipcRenderer.on('log:line', (_, line) => cb(line)),
    offLogLine: () => ipcRenderer.removeAllListeners('log:line'),
    onAdminStatus: (cb: (ok: boolean) => void) => ipcRenderer.on('admin:status', (_, ok) => cb(ok)),
    openDialog: (opts: any) => ipcRenderer.invoke('dialog:open', opts),
    saveDialog: (opts: any) => ipcRenderer.invoke('dialog:save', opts),
})
